server:
  port: 8081
logging:
  level:
    root: INFO


spring:
  application:
    name: @pom.artifactId@
  security:
    user:
      name: "admin"
      password: "admin"
  profiles:
    active: @env@
  #404 处理
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

  # jackson 配置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: NON_NULL
    time-zone: GMT+8

  # 数据库配置
  datasource:
    url: jdbc:mysql://192.168.2.11:3306/calf_user?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource

  #redis 配置
  redis:
    host: 192.168.2.11
    port: 6444
    timeout: 3000ms
    database: 0
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1ms
  #mongodb 配置
  data:
    mongodb:
      uri: mongodb://root:123456@192.168.2.11:27017/test?authSource=admin&authMechanism=SCRAM-SHA-1
      auto-index-creation: true


mybatis-plus:
  # 配置扫描xml
  mapper-locations:
    - classpath:mapper/*.xml
  # 实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.calf.cloud.uaa.pojo.entity
  global-config:
    # 逻辑删除配置
    db-config:
      logic-delete-value: 0
      logic-not-delete-value: 1
    banner: false
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl




eureka:
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:${eureka.instance.port}/eureka/
    registryFetchIntervalSeconds: 5 #eureka client 获取注册信息列表并缓存到本地，之后只会增量获取信息，获取注册信息的操作是一个异步任务，默认每隔30秒执行一次
  instance:
    hostname: 127.0.0.1
    port: 8055
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    leaseRenewalIntervalInSeconds: 5 # 心跳时间，即服务续约间隔时间（缺省为30s）
    leaseExpirationDurationInSeconds: 10 # 发呆时间，即服务续约到期时间（缺省为90s）


feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true
  client:
    config:
      default:
        connect-timeout: 10000 # 单位毫秒
        read-timeout: 3600000 # 单位毫秒，兼容报表查询等，设置为60分钟
springfox:
  documentation:
    enabled: true



calf-cloud:
  swagger:
    enabled: true
    title: 文档管理-用户模块
    version: V0.0.1
    description: 用户模块-文档管理
    author: fengzijk
    email: guozhifengvip@gmail.com
    requestParameter: true
    termsOfServiceUrl: http//:fengzijk.com
    basePackage:
      - com.calf.cloud.user.controller

  global-response:
    adviceFilterClass:
      - springfox.documentation
      - org.springframework
  redis:
    enabled: true
    redissonLockEnable: true
  security:
    enable: true
    ignore:
      urls:
        - /v3/api-docs/**
