#spring:
#  #redis 配置
#  redis:
#    host: 192.168.2.11
#    port: 6379
#    timeout: 3000ms
#    database: 0
#    password: 123456
#    jedis:
#      pool:
#        max-active: 8
#        max-idle: 8
#        min-idle: 0
#        max-wait: -1ms