server:
  port: 9088
logging:
  level:
    root: INFO
    org.springframework.web: info




spring:
  application:
    name: @pom.artifactId@
  profiles:
    active: @env@
  security:
    user:
      name: "admin"
      password: "admin"

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
      routes:
        - id: calf-cloud-uaa
          uri: lb://CALF-CLOUD-UAA
          predicates:
            - Path=/uaa/**
          filters:
            - StripPrefix=1
  #redis 配置
  redis:
    host: 192.168.2.11
    port: 6379
    timeout: 3000ms
    database: 0
    password: 123456
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1ms




eureka:
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:${eureka.instance.port}/eureka/
    registryFetchIntervalSeconds: 5 #eureka client 获取注册信息列表并缓存到本地，之后只会增量获取信息，获取注册信息的操作是一个异步任务，默认每隔30秒执行一次
  instance:
    port: 8055
    hostname: 127.0.0.1
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    leaseRenewalIntervalInSeconds: 5 # 心跳时间，即服务续约间隔时间（缺省为30s）
    leaseExpirationDurationInSeconds: 10 # 发呆时间，即服务续约到期时间（缺省为90s）


management:
  endpoints:
    web:
      exposure:
        include: "*"  #<2>
  endpoint:
    health:
      show-details: ALWAYS
springfox:
  documentation:
    enabled: true

swagger:
  enabled: true

global-response:
  adviceFilterPackage:
    - springfox.documentation
    - org.springframework